[package]
name = "wnf"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.31"

[dependencies.windows]
version = "0.36.1"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_SystemServices"
]
