[package]
name = "wnf"
version = "0.1.0"
edition = "2021"

[features]
bytemuck-v1 = ["dep:bytemuck-v1"]
zerocopy = ["dep:zerocopy"]

[dependencies]
bytemuck-v1 = { package = "bytemuck", version = "1.12.0", optional = true }
num-derive = "0.3.3"
num-traits = "0.2.15"
thiserror = "1.0.31"
tracing = { version = "0.1.34", features = ["log"] }
windows = { version = "0.39.0", features = ["Win32_Foundation", "Win32_Security", "Win32_System_SystemServices"] }
zerocopy = { version = "0.6.1", optional = true }

[dev-dependencies]
tokio = { version = "1.20.0", features = ["macros", "rt-multi-thread", "time"] }
tracing-subscriber = { version = "0.3.11", features = ["fmt"] }
