[package]
name = "devutils"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
libtest-mimic = "0.5.2"
tempfile = "3.3.0"
windows = { version = "0.39.0", features = ["Win32_Foundation", "Win32_System_Registry", "Win32_UI_Shell"] }
