name: Audit

on:
  - workflow_call
  - workflow_dispatch

env:
  RUSTFLAGS: --deny warnings

jobs:
  audit:
    name: Audit
    runs-on: windows-latest

    steps:
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run audit
        run: cargo audit
