name: Beta

on:
  schedule:
    # new Rust versions are released on Thursdays -> run every Friday at 12pm
    - cron: "0 12 * * FRI"
  workflow_call:
  workflow_dispatch:

env:
  RUSTFLAGS: --deny warnings
  WNF_SYSTEM_TESTS_ENABLED: 1

jobs:
  test:
    name: Test (on beta)
    runs-on: windows-latest

    steps:
      - name: Install beta toolchain
        uses: dtolnay/rust-toolchain@beta

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: cargo test --all-features
