name: Doc

on:
  - workflow_call
  - workflow_dispatch

env:
  RUSTFLAGS: --deny warnings

jobs:
  fmt-check:
    name: Doc
    runs-on: windows-latest

    steps:
      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docs
        run: cargo rustdoc --all-features --target x86_64-pc-windows-msvc -- --cfg docsrs
