name: Format check

on:
  - workflow_call
  - workflow_dispatch

env:
  RUSTFLAGS: --deny warnings

jobs:
  fmt-check:
    name: Format check
    runs-on: windows-latest

    steps:
      - name: Install nightly toolchain with rustfmt
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run format check
        run: cargo fmt --check
