name: Minimal versions

on:
  - workflow_call
  - workflow_dispatch

env:
  RUSTFLAGS: --deny warnings
  WNF_SYSTEM_TESTS_ENABLED: 1

jobs:
  test:
    name: Test using minimal dependency versions
    runs-on: windows-latest

    steps:
      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install minimal dependency versions
        run: cargo +nightly update -Zminimal-versions

      - name: Check
        # Cannot run tests or run `cargo check --all-targets`
        # because `devutils` fails due to conflicting versions of `winapi`
        run: cargo +stable check --all-features
