name: Minimal versions

on:
  - workflow_call
  - workflow_dispatch

env:
  RUSTFLAGS: --deny warnings
  WNF_SYSTEM_TESTS_ENABLED: 1

jobs:
  test:
    name: Test using minimal dependency versions
    runs-on: windows-latest

    steps:
      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install minimal dependency versions
        run: cargo update -Zminimal-versions

      - name: Run tests
        run: cargo test --all-features
