name: Miri

on:
  - workflow_call
  - workflow_dispatch

env:
  RUSTFLAGS: --deny warnings

jobs:
  miri:
    name: Miri
    runs-on: windows-latest

    steps:
      - name: Install nightly toolchain with Miri
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri

      - name: Setup Miri
        run: cargo miri setup

      - name: Checkout
        uses: actions/checkout@v5

      - name: Run lib tests under Miri
        run: cargo miri test --lib
