name: MSRV

on:
  - pull_request
  - workflow_call
  - workflow_dispatch

env:
  RUSTFLAGS: --deny warnings

jobs:
  check:
    name: Check using minimal supported Rust version
    runs-on: windows-latest

    steps:
      - name: Install MSRV toolchain
        uses: dtolnay/rust-toolchain@1.62

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check
        run: cargo check --all-features --all-targets
