name: MSRV

on:
  - workflow_call
  - workflow_dispatch

env:
  RUSTFLAGS: --deny warnings

jobs:
  check:
    name: Check using minimal supported Rust version
    runs-on: windows-latest

    steps:
      - name: Install MSRV toolchain
        uses: dtolnay/rust-toolchain@1.74

      - name: Checkout
        uses: actions/checkout@v4

      # The Cargo.toml of `bytemuck-derive` cannot be parsed with Cargo 1.74 because it contains the setting `resolver = "3"`.
      # Since `bytemuck-derive` is only used in tests and doctests, which we do not run (nor check) here, we don't need it for the MSRV check.
      - name: Remove dev-dependency on `bytemuck` with `derive` feature
        run: Set-Content -Path Cargo.toml -Value (Get-Content -Path Cargo.toml | Select-String -Pattern 'remove-for-msrv-check' -NotMatch)

      - name: Check
        run: cargo check --all-features --lib
